version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
